<?php

//************************************************************
// Deals with Autocomplete of Pay Later for admin screen
//************************************************************
/**
 * Implements hook_action_info()
 * Creates a VBO Action to Complete a Pay Later Contribution.
 */
function lalg_dutils_action_info() {
	//dpm('Hook Action Info called');
  return array(
    'lalg_dutils_complete_pay_later_contribution' => array(
      'type' => 'entity',
      'label' => t('Complete payment for a Pending Contribution'),
      'behavior' => array('changes_property'),
      'configurable' => FALSE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Carries out the Complete Payment Action
 */
function lalg_dutils_complete_pay_later_contribution(&$entity, $context) {
	//dpm('VBO Action');
//	dpm($entity);
//	dpm($context);
	
	if ($context['entity_type'] != 'civicrm_contribution' ) return;
	if ($entity -> contribution_status != 'Pending' ) return;
	$cid = $entity -> contribution_id;
//	dpm($cid);

// Call the API to trigger the dependent actions - update Membership and send email 
//	dpm('VBO Completing the Contribution');
	$result = civicrm_api3('Contribution', 'completetransaction', [
		'id' => $cid,
		'total_amount' => $entity -> total_amount,
		'financial_type' => 2,									// Membership Dues
	]);
//	dpm($result);
	
// The system will now save the Drupal Entity which is mirroring the CiviCRM one, 
//  and thus overwrite changes made via the API.
//  So update the critical items 'by hand' before this happens.	
	$contribution_entity = entity_load_single('civicrm_contribution', $cid);
//	dpm($contribution_entity);
	
	$contribution_entity -> contribution_status_id = 1;				// Complete
	$contribution_entity -> contribution_status = 'Complete';		// Belt and Braces
	$contribution_entity -> payment_instrument_id = 6;				// Not Tracked
	$contribution_entity -> instrument_id = 6;						// Belt and Braces	
	$contribution_entity -> payment_instrument = 'Not Tracked';		// Belt and Braces
//	entity_save('civicrm_contribution', $contribution_entity);
}


//********************************************************************
// Custom Webform Validation Rules
//********************************************************************

/**
 * Implements hook_webform_validation_validators().
 */
function lalg_dutils_webform_validation_validators() {
  return array(
    'all_or_none' => array(
      'name' => "LALG All or None",
      'description' => "Checks all or none of the specified fields have content.",
      'component_types' => array(
        'textfield', 'email',
      ),
    ),
	'lalg_email_dependencies' => array(
      'name' => "LALG Email Dependencies",
      'description' => "Checks dependencies on Email field. Select Membership Type, Last Name and Email",
      'component_types' => array(
        'textfield', 'email', 'select',
      ),	 
	)
  );
}

/**
 * Implements hook_webform_validation_validate().
 */
function lalg_dutils_webform_validation_validate($validator_name, $items, $components, $rule) {
  if ($items) {
    switch ($validator_name) {
		
// ****************  All or None Validator  ***********************		
      case 'all_or_none':
// dpm($items);	  
        $errors = array();
        foreach ($items as $key => $val) {
			$items[$key] = (bool) strlen($items[$key]);
        }
		$number_completed = count(array_filter($items));
		if ($number_completed > 0 && $number_completed < count($items) ) {
			// Generate Error Message(s)
			if (count($items) == 2) {
				$err_message = 'You must complete both or neither of the First/Last Name';
			}
			else {
				$err_message = 'You must complete all or none of the First/Last Name and Email Address';
			}
			reset($items);
			$errors[key($items)] = $err_message;
		}
        return $errors;
        break;
		
// *********************  Email Dependencies Validator  **************************
/* Implements a custom validation rule.
 * Requires the following fields selected:  Email, Last Name of same Contact, Send Membership Documents, ditto,
 *   and Membership Type Required.
 * Error if Email and no Last Name, or Plain Membership and no Email.
 */
	  case 'lalg_email_dependencies':
	  
// dpm($items);
// dpm($components);		
        $errors = array();
		foreach ($items as $key => $val) {
			// Identify the fields of interest
			$formKey = $components[$key]['form_key'];
			if (endsWith($formKey, 'email')) {$email = $key;} 
			if (endsWith($formKey, 'name')) {$name = $key;}
			if (endsWith($formKey, 'membership_type_id')) {$membId = $key;}
		}	

 // dpm('Email: ' . $email . 'Value: ' . $items[$email]);
  
		if ($items[$email] && !$items[$name]) {
			// Email set but no Name
			$errors[$name] = 'Name is mandatory if Email field is set';
		}
		if (!$items[$email] && $items[$name])  {
			// Email field empty - check other dependencies	
			if ($items[$membId] == '7') {
				$errors[$email] = 'Membership without a Printed Newsletter requires an Email address';
			}			
		}

		// Return any errors		
        return $errors; 
		break;
    }
  }
}

function endsWith($haystack, $needle)
{
    $length = strlen($needle);
    if ($length == 0) {
        return true;
    }
    return (substr($haystack, -$length) === $needle);
}

//********************************************************************
// Changes to Webforms - in addition to the standard configuration stuff
//********************************************************************
/**
 * Implements hook_form_alter().
 */
function lalg_dutils_form_webform_client_form_alter(&$form, &$form_state, $form_id) {
//dpm($form_id);

//************  Attach Javascript to Webforms for behaviour tweaks. ************
	$path = drupal_get_path('module', 'lalg_dutils') . '/lalg_webform.js';
	//dpm($path);
    $form['#attached']['js'][] = $path;
  
//************  Add Membership Price Information  *****************
  if ($form['progressbar']['#page_num'] == '1') {	
// dpm($form);
	// Find the Price Details
	$prices = lalg_get_price_data();
	// Add to form
	if (isset($form['submitted']['membership_details']['#description'])) {
	  $form['submitted']['membership_details']['#description'] .= $prices;
	}
  }
  
//********************* Copy Postcode if HH not set yet *************************
// Usability, if User has registered with Postcode it then shows on Webform.
  if ($form['progressbar']['#page_num'] == '1' && $form_id == 'webform_client_form_8017')  {	
//  dpm($form);
//  dpm($form_id);
	// Get current Contact Id
	$cid = CRM_Core_Session::singleton()->getLoggedInContactID();
//	dpm($cid);
	// Get their Postcode
	$result = civicrm_api3('Contact', 'get', [
	  'sequential' => 1,
	  'return' => ["postal_code"],
	  'id' => $cid,
	]);
	$postcode = $result['values'][0]['postal_code'];
//	dpm($postcode);
	// Set default value for HH Postcode
	$form['submitted']['civicrm_2_contact_1_fieldset_fieldset']['civicrm_2_contact_1_address_postal_code']['#default_value'] = $postcode;
  }
}

// ****************** Helper Routine ********************
// Extracts and formats the help text containing Membership types and prices
function lalg_get_price_data() {
//dpm('Get Price Data');
  // Check for cached copy
  $prices = &drupal_static(__FUNCTION__);
  if (!isset($prices)) {
    if ($cache = cache_get('lalg_membership_prices')) {
	$prices = $cache->data;
    }
    else {
		// Do the hard work, and populate $prices
		// Get all Active Membership Types
		$result = civicrm_api3('MembershipType', 'get', [
		  'sequential' => 1,
		  'is_active' => 1,
		]);
//dpm($result);

		// Build the Help Text
		$prices = 'Membership Prices: </br>'; 
		foreach ($result['values'] as $value) {
//			dpm($value);
			$prices .= '&nbsp;&nbsp;&nbsp;' . $value['name'] . ' -- £';
			$prices .= number_format((float)$value['minimum_fee'], 2);
		}
      // Save back in the cache
      cache_set('lalg_membership_prices', $prices, 'cache', time() + 7200);		// Actually will be cleared when cron runs - max life two hours
    }
  }
  return $prices;
}


